### ISSUE TITLE
Support boks

### ISSUE THREAD

**Issue by billbindi** [kizyahaha/MSB_website_design#13]
A currency system for performing actions on the site. Depending on how it is gamified, this might also be used to purchase power ups?

**Comment by kizyahaha** [comment]
We need to hammer out the deets as to what costs and what gains boks.  This will be a very delicate balancing act, so it might just take some experimentation and on the fly changes in the early stages of the site launch.  For example, if we charge people too much to vote, then they just won't vote.  If we pay people too much to vote, then they will vote indiscriminately.  The balance is somewhere in the middle.  We want to encourage and reward people for voting without encouraging game hackers.

**Comment by kizyahaha** [comment]
Duplicate with dual currency system which we decided to use
