### ISSUE TITLE
Should the level winner display have options for voting and applying items?

### ISSUE THREAD

**Issue by kizyahaha** [kizyahaha/MSB_website_design#143]
The concern is that this would be the ultimate front page bias.

But every rant that wins will have gone through this.  So in theory, no matter if it's a benefit or a hindrance, it should still be "even" with every other rant in the next level.
- Eh, kind of.  There is still a time of day bias here

How do we really even prevent people from voting or applying items if they want?  Will the title no longer link to the DRV?  Will the author's name no longer link to their profile which would link to the rant?  It just seems like too much of a special case.

**Comment by billbindi** [comment]
Treat it like a normal rant. If you can vote and apply items on a normal rant, then yes allow it. Maybe it can just be a rant preview, but I think the level winners should be a full DRV.
