### ISSUE TITLE
Users who have not submitted rants cannot log in

### ISSUE THREAD

**Issue by kizyahaha** [kizyahaha/MSB_website_design#163]

**Comment by billbindi** [comment]
Are you sure? I just tried logging in as test/test, and it worked. What user in particular did you try logging in with that didn't work?

**Comment by kizyahaha** [comment]
All of them....I'll investigate further.

Did you do a pull before trying this?  I wonder if it might be the new modal log in?

**Comment by billbindi** [comment]
I did, and I used the modal to do the log in. Then I went to the My Profile page and said my username was "test" as I would expect.

**Comment by kizyahaha** [comment]
Ok, I have no idea what happened.  Even after you said you couldn't repeat it, I was able to repeat it even after stopping and restarting the server.  It was saying index 8 was out of range in parseUser.....But after I did a pull and rebase it went away.  So for now I'll just close this until it pops up again.
