### ISSUE TITLE
ctrl+z

### ISSUE THREAD

**Issue by kizyahaha** [kizyahaha/MSB_website_design#179]
Is this sort of thing handled naturally by the browser?  It kinda seems like yes.  But what are it's limitations?

**Comment by billbindi** [comment]
It probably will be for text editing, but it will not be for things like undoing a vote, or using an item.

**Comment by kizyahaha** [comment]
I imagine text editing is all we will want though.
- Votes can be taken back just by clicking the button again.
- I don't think we want to provide the ability to take items back.  That leads to a really messy web of tracking all the item's effects and undoing all of them.  What is the statute of limitations on that take back?  And what if you apply an item on my rant and as a direct result, I apply an item on my rant to counter the effect of your item?  Do I get to take my item back?  It's just too messy.  I think anyone who has ever played a video game before will accept the limitations of that.
- I would also favor not allowing a true "take back" of an in-site purchase either.  But we could (and should in my opinion) have a sell back option.  So for example, if you buy an item for 100 boks, you can sell it back for 60 boks or something.

How do we want to handle real world purchases?  If someone pays $5 for 500 boks, can they ever get their money back?

**Comment by kizyahaha** [comment]
Bill and I agree, only takesy backsies in text editing which is handled by the browser.
