### ISSUE TITLE
Cannot create new line when making a rant

### ISSUE THREAD

**Issue by kizyahaha** [kizyahaha/MSB_website_design#196]
Hitting enter submits the rant.  Maybe just get rid of this so you actually have to click the submit button?

**Comment by billbindi** [comment]
A not-too-uncommon thing is to have something like CTRL+ENTER be the submit shortcut, and normal ENTER be a newline in the text. How hard is something like this?

**Comment by kizyahaha** [comment]
ctrl + enter it is
