### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by kizyahaha** [kizyahaha/MSB_website_design#206]
Do we need it?  If so, where?  How do we get it?

**Comment by billbindi** [comment]
NOOOO! We will need to do secure transactions with money, but the site should absolutely not be behind https!

**Comment by kizyahaha** [comment]
NOOOO?

**Comment by kizyahaha** [comment]
Most likely we won't be directly gathering people's sensitive information like credit cards.  HTTPS complicates things and it might not be necessary for us.
