### ISSUE TITLE
Associate rant objects with users

### ISSUE THREAD

**Issue by kizyahaha** [kizyahaha/MSB_website_design#46]
When requesting user info, the format for the rants that they created which was returned to the front end used to be entire rant objects.  Now we just get a collection rant id's which means I have to do a separate request to get each rant's info in order to display the My Rants tab.  Can we switch it back to returning the rant objects?

**Comment by billbindi** [comment]
Hmm...This can't be possible since it would mean that what it returns to the front end is infinitely long. For example:

```
    user = {
      name = "name",
      id = 0,
      email = "abc@email.com",
      rants = {
        id = 0,
        title = "title",
        contents = "contents",
        owner = {
            name = "name",
            id = 0,
            email = "abc@email.com",
            rants = {
              id = 0,
              title = "title",
              contents = "contents",
              owner = {
                // etc...
              }
            }
          }
        }
      }
    }
```
