### ISSUE TITLE
Do we want to limit one account per email address?

### ISSUE THREAD

**Issue by kizyahaha** [kizyahaha/MSB_website_design#95]
If yes, we need to check the current list of users when creating a user and issue a specific warning in the event that the email is already used.  We'd also have to check for email duplicates when a user tries to update their email.

**Comment by billbindi** [comment]
We should definitely do this

**Comment by kizyahaha** [comment]
The check for duplicate emails and usernames on sign up is in place (have Bill check back end code to return an int, not a string).

How do we want to deal with changing an email?  For sure still check against existing emails, but do we want to send an email confirmation?  I'd think yes else someone can (maybe?) write a bot to sign up with valid_email@email.com, change the email to garbage_email@garbage.com, then sign up again with valid_email@email.com, and loop indefinitely to create as many accounts as they want.

**Comment by kizyahaha** [comment]
Yes, we need a confirmation on change as well.  Bill declares and I agree.

**Comment by kizyahaha** [comment]
The check for email duplicates is done.  The email confirmation issue is mentioned elsewhere.  So I'm closing this.
